# Generated by Django 4.2.13 on 2026-04-19 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pqrsd', '0002_omnicanal_meta'),
        ('conocimiento', '0002_synclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorradorRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_borrador', models.TextField()),
                ('texto_editado', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revisado', 'Revisado por funcionario'), ('enviado', 'Enviado al ciudadano')], default='borrador', max_length=20)),
                ('modelo_ia', models.CharField(default='gemini-1.5-flash', max_length=50)),
                ('prompt_usado', models.TextField(blank=True)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('pqrsd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borradores', to='pqrsd.pqrsd')),
                ('precedentes_usados', models.ManyToManyField(blank=True, to='conocimiento.precedenterespuesta')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borradores_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Borrador de Respuesta',
                'verbose_name_plural': 'Borradores de Respuesta',
                'ordering': ['-generado_en'],
            },
        ),
    ]
